import { blockScalar, quote, isValidName, assertNoSecrets } from "./yaml.js";
import { lookupPreset } from "./presets.js";

/**
 * Parse a --tools value: `server:tool1,tool2`.
 *
 * The allowlist is REQUIRED. `--tools kagent-tool-server` with no tool names
 * is refused rather than defaulting to "every tool the server offers" — a
 * scaffolder that can silently widen an agent's reach is a liability, and the
 * whole point of the tools block is that the surface is enumerated in the
 * YAML where a reviewer can see it.
 *
 * Tool names are validated, not just trimmed. Emitted as a bare YAML scalar,
 * a name containing a newline could close the sequence and open new keys —
 * `--tools 'srv:ok\n            - secret_tool'` would grant a capability
 * nobody reviewed. MCP tool names are identifiers, so the safe set is small
 * and an exact match is cheap.
 */
const TOOL_NAME = /^[A-Za-z_][A-Za-z0-9_.-]{0,127}$/;

export function parseToolSpec(spec) {
  const raw = String(spec);
  // Split on the FIRST colon only: a stray colon later is part of the list
  // and will fail tool-name validation rather than being silently dropped.
  const sep = raw.indexOf(":");
  const server = sep === -1 ? raw : raw.slice(0, sep);
  const list = sep === -1 ? undefined : raw.slice(sep + 1);

  if (!server || !isValidName(server)) {
    throw new Error(`--tools: '${spec}' does not start with a valid server name`);
  }
  if (list === undefined || list.trim() === "") {
    throw new Error(
      `--tools: '${spec}' has no tool allowlist. Use ${server}:<tool>[,<tool>...] — ` +
        `an agent is never wired to every tool a server offers.`,
    );
  }
  const tools = list.split(",").map((t) => t.trim()).filter(Boolean);
  if (tools.length === 0) {
    throw new Error(`--tools: '${spec}' has an empty tool allowlist`);
  }
  for (const t of tools) {
    if (!TOOL_NAME.test(t)) {
      throw new Error(
        `--tools: '${t}' is not a valid tool name. Expected an identifier ` +
          `(letters, digits, '_', '.', '-'), so a name cannot break out of the YAML list.`,
      );
    }
  }
  return { server, tools };
}

/**
 * Build the Agent manifest. Returns YAML text; writing and applying are
 * someone else's job, so this stays pure and testable.
 */
export function renderAgent({
  name,
  namespace = "kagent",
  modelConfig,
  description,
  instructions,
  tools = [],
}) {
  if (!isValidName(name)) {
    throw new Error(
      `'${name}' is not a valid Kubernetes name. Use lower-case letters, ` +
        `digits and '-', starting and ending alphanumeric (RFC 1123), max 63 chars.`,
    );
  }
  if (!isValidName(namespace)) {
    throw new Error(`'${namespace}' is not a valid namespace name`);
  }
  if (!instructions || !String(instructions).trim()) {
    throw new Error("an agent needs instructions — pass --instructions <file>");
  }

  const preset = lookupPreset(modelConfig);

  const header = [
    `# Generated by kaimahi agent create.`,
    `#`,
    `# This file is the agent: its topology is reviewable YAML, and it is yours`,
    `# from here — edit it, diff it, commit it, kubectl apply it.`,
    `#`,
    `# Model preset: ${modelConfig} — ${preset.summary}`,
    preset.governed
      ? `# GOVERNED: calls route through the Kaimahi proxy and are metered,\n#   budget-checked, and ledgered. The Secret below holds a Kaimahi-issued\n#   token, never a real upstream key.`
      : `# UNGOVERNED: calls go straight to the provider. No budget, no ledger,\n#   no audit. Consider a governed-* preset instead.`,
  ].join("\n");

  const lines = [
    header,
    `apiVersion: kagent.dev/v1alpha2`,
    `kind: Agent`,
    `metadata:`,
    `  name: ${name}`,
    `  namespace: ${namespace}`,
    `spec:`,
    `  description: ${quote(description || `Agent ${name}, scaffolded by kaimahi.`)}`,
    `  type: Declarative`,
    `  declarative:`,
    `    modelConfig: ${modelConfig}`,
    `    systemMessage: ${blockScalar(instructions, 6)}`,
  ];

  if (tools.length > 0) {
    lines.push(`    tools:`);
    for (const { server, tools: allow } of tools) {
      lines.push(
        `      - type: McpServer`,
        `        mcpServer:`,
        `          apiGroup: kagent.dev`,
        `          kind: RemoteMCPServer`,
        `          name: ${server}`,
        `          toolNames:`,
        // Quoted as well as validated. Validation is the real defence; the
        // quotes mean a future loosening of TOOL_NAME cannot silently become
        // a YAML-injection bug.
        ...allow.map((t) => `            - ${quote(t)}`),
      );
    }
  }

  const yaml = lines.join("\n") + "\n";
  assertNoSecrets(yaml, `the manifest for '${name}'`);
  return yaml;
}
