import { blockScalar, quote, isValidName, assertNoSecrets } from "./yaml.js";
import { lookupPreset } from "./presets.js";

/**
 * Parse a --tools value: `server:tool1,tool2`.
 *
 * The allowlist is REQUIRED. `--tools kagent-tool-server` with no tool names
 * is refused rather than defaulting to "every tool the server offers" — a
 * scaffolder that can silently widen an agent's reach is a liability, and the
 * whole point of the tools block is that the surface is enumerated in the
 * YAML where a reviewer can see it.
 */
export function parseToolSpec(spec) {
  const [server, list] = String(spec).split(":");
  if (!server || !isValidName(server)) {
    throw new Error(`--tools: '${spec}' does not start with a valid server name`);
  }
  if (list === undefined || list.trim() === "") {
    throw new Error(
      `--tools: '${spec}' has no tool allowlist. Use ${server}:<tool>[,<tool>...] — ` +
        `an agent is never wired to every tool a server offers.`,
    );
  }
  const tools = list.split(",").map((t) => t.trim()).filter(Boolean);
  if (tools.length === 0) {
    throw new Error(`--tools: '${spec}' has an empty tool allowlist`);
  }
  return { server, tools };
}

/**
 * Build the Agent manifest. Returns YAML text; writing and applying are
 * someone else's job, so this stays pure and testable.
 */
export function renderAgent({
  name,
  namespace = "kagent",
  modelConfig,
  description,
  instructions,
  tools = [],
}) {
  if (!isValidName(name)) {
    throw new Error(
      `'${name}' is not a valid Kubernetes name. Use lower-case letters, ` +
        `digits and '-', starting and ending alphanumeric (RFC 1123), max 63 chars.`,
    );
  }
  if (!isValidName(namespace)) {
    throw new Error(`'${namespace}' is not a valid namespace name`);
  }
  if (!instructions || !String(instructions).trim()) {
    throw new Error("an agent needs instructions — pass --instructions <file>");
  }

  const preset = lookupPreset(modelConfig);

  const header = [
    `# Generated by kaimahi agent create.`,
    `#`,
    `# This file is the agent: its topology is reviewable YAML, and it is yours`,
    `# from here — edit it, diff it, commit it, kubectl apply it.`,
    `#`,
    `# Model preset: ${modelConfig} — ${preset.summary}`,
    preset.governed
      ? `# GOVERNED: calls route through the Kaimahi proxy and are metered,\n#   budget-checked, and ledgered. The Secret below holds a Kaimahi-issued\n#   token, never a real upstream key.`
      : `# UNGOVERNED: calls go straight to the provider. No budget, no ledger,\n#   no audit. Consider a governed-* preset instead.`,
  ].join("\n");

  const lines = [
    header,
    `apiVersion: kagent.dev/v1alpha2`,
    `kind: Agent`,
    `metadata:`,
    `  name: ${name}`,
    `  namespace: ${namespace}`,
    `spec:`,
    `  description: ${quote(description || `Agent ${name}, scaffolded by kaimahi.`)}`,
    `  type: Declarative`,
    `  declarative:`,
    `    modelConfig: ${modelConfig}`,
    `    systemMessage: ${blockScalar(instructions, 6)}`,
  ];

  if (tools.length > 0) {
    lines.push(`    tools:`);
    for (const { server, tools: allow } of tools) {
      lines.push(
        `      - type: McpServer`,
        `        mcpServer:`,
        `          apiGroup: kagent.dev`,
        `          kind: RemoteMCPServer`,
        `          name: ${server}`,
        `          toolNames:`,
        ...allow.map((t) => `            - ${t}`),
      );
    }
  }

  const yaml = lines.join("\n") + "\n";
  assertNoSecrets(yaml, `the manifest for '${name}'`);
  return yaml;
}
